.TH "CImgRGB" 3 "Fri Jun 8 2018" "Flood Fill Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CImgRGB
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCImgRGB\fP (Uint32)"
.br
.ti -1c
.RI "\fBCImgRGB\fP (Uint16, Uint16, Uint16)"
.br
.ti -1c
.RI "void \fBgetRGBToBitmap\fP (CImg< Uint16 > *, size_t, size_t)"
.br
.ti -1c
.RI "Uint32 \fBgetRGBcolor\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Flood Fill Algorithm from the source code\&.
